### ISSUE TITLE
subtitles stop working after one scene

### ISSUE THREAD

**Issue by silvercrest7** [Terminality/HSceneSubtitler#1]
The subtitles work fine but only for one H-scene and and every scene after only H SCENE SUBTITLES ENABLED is shown at the top of the screen and stays that way till the game is restated

Edit
it might have something to do with multiple girls in a room
subtitles continue to work fine in a room with only one girl

seems like it is cause when there is a change from one girl to another with different personality/voice

**Comment by Terminality** [comment]
Taking a look at it now, I see what you mean. Just trying to figure out the exact issue going on.

**Comment by Terminality** [comment]
Fixed.
